### ISSUE TITLE
Navigate between the various areas of the system

### ISSUE THREAD

**Issue by jared-benade** [jaydpage/journeyman#9]
As a user I expect to be able to navigate between the various areas of the system (eg; between journeys, tasks, etc)

**Comment by jared-benade** [comment]
Should we investigate react router for this? Having nicely defined URLs to share with others (eg: your manager) could be quite useful and I think this will be easier to implement early in the system's life.

**Comment by jaydpage** [comment]
I agree that routing and links could be useful, specifically to view another users journey, which we may want to do in the future. I think it would provide a better user experience than a SPA. However I think we can still have certain dashboard like pages that show multiple components on a single route.

**Comment by jaydpage** [comment]
I have implemented react router and the page navigation and routing is working
